### ISSUE TITLE
Feature Request: Filter by property which is passed as a string variable

### ISSUE THREAD

**Issue by prochnowc** [ZEXSM/OData.QueryBuilder#101]
Hi,

I have a use case where the user can enter the name of the property which should be used to filter the result set.
Currently this is not possible because

```
string propertyName = "myProperty";
builder.Filter(e => propertyName == "test")
```

is being rendered as 

`propertyName eq 'test'`

instead of the wanted

`myProperty eq 'test'`

Do you think you can add such feature ?
Eg. by passing a special static function like so:

```
Filter(e => ODataProperty.ByName(propertyName) == "value")
```

Thanks in advance!

**Comment by ZEXSM** [comment]
Hi!

Please attach a complete usage example, starting with creating an ODataQueryBuilder instance.

Do I understand correctly that there is a need for a dynamic property name?

**Comment by prochnowc** [comment]
> Do I understand correctly that there is a need for a dynamic property name?

yes


A complete example would be:

```csharp
string propertyName = "ODataKind.ODataCode.IdCode";
new ODataQueryBuilder()
  .For<ODataTypeEntity>()
  .ByList()
  .Filter((s,f,_) => f.Property<int>(propertyName) >= 3)
  .ToUri();
```

**Comment by ZEXSM** [comment]
> > Do I understand correctly that there is a need for a dynamic property name?
> 
> yes
> 
> A complete example would be:
> 
> ```cs
> string propertyName = "ODataKind.ODataCode.IdCode";
> new ODataQueryBuilder()
>   .For<ODataTypeEntity>()
>   .ByList()
>   .Filter((s,f,_) => f.Property<int>(propertyName) >= 3)
>   .ToUri();
> ```

Possibly related https://github.com/ZEXSM/OData.QueryBuilder/issues/99

**Comment by prochnowc** [comment]
What do you think about the PR @ZEXSM ?
