### ISSUE TITLE
Use guids as keys in ByKey Method

### ISSUE THREAD

**Issue by christophanneken** [ZEXSM/OData.QueryBuilder#55]
In our project we use Guids as keys

```C#
var uri = new ODataQueryBuilder<ODataInfoContainer>("http://mock/odata")
    .For<ODataTypeEntity>(s => s.ODataType)
    .ByKey(295b2f1d-a17e-4d26-bcfb-c8f79d023763)
    .ToUri()
```

Inserting the guid as string results in wrong urls. It would be great if the ByKey method could be extended to use guids.

**Comment by ZEXSM** [comment]
Hey! I have made a change, could you please watch this
https://github.com/ZEXSM/OData.QueryBuilder/tree/bugfix/use-guid-bykey#-bykey

is that what you need?

**Comment by christophanneken** [comment]
Hi, exactly what I needed! Thanks a lot
