### ISSUE TITLE
Error on IODataExpandResource.For in Expand

### ISSUE THREAD

**Issue by szymonjagiello86** [ZEXSM/OData.QueryBuilder#78]
Hi,
we are getting "System.IndexOutOfRangeException: Index was outside the bounds of the array" when we use the For method without additional operations:

.Expand(e => e.For<ChildEntity>(ee => ee.childEntity).Filter(eee => eee.Id)) //works

.Expand(e => e.For<ChildEntity>(ee => ee.childEntity)) //throws exception

**Comment by ZEXSM** [comment]
Hi! I am currently working on removing this exception, but for now, for a simple Expand, use

`.Expand (e => e.childEntity)`

**Comment by szymonjagiello86** [comment]
Hi!
I confirm that the bug has been fixed. Thank you for support!

Br,
Szymon
