### ISSUE TITLE
StringExtensions.ToQuery() does not support some types

### ISSUE THREAD

**Issue by Pisaren** [ZEXSM/OData.QueryBuilder#82]
For example StringExtensions.ToQuery() does not process correctly `IEnumerable<long>` and in that case returns "System.Int64[]" string.
Also it doesn't support `IEnumerable<byte>`, `IEnumerable<short>`, `IEnumerable<DateTime>`.

**Comment by ZEXSM** [comment]
Give an example in the format expectation is reality

**Comment by Pisaren** [comment]
Sorry, did not check how my previous message was shown. Edited it.
When I execute next code
```
var builder = new ODataQueryBuilder().For<Model>("model").ByList().Filter((x, _, o) => o.In(x.LongId, new long [] { (long)0, (long)-5 }));
var uri = builder.ToUri();
```
I get `model?$filter=LongId in ('System.Int64[]')`, but expect `model?$filter=LongId in (0,-5)`
