### ISSUE TITLE
ODataQuery.ToDictionary() returns not all items

### ISSUE THREAD

**Issue by Pisaren** [ZEXSM/OData.QueryBuilder#83]
In case when ODataQuery was instantiated with empty StringBuilder (without baseUrl or baseUrl equal to empty string) then reading split string from second element (index=1) skips first URL parameter.

**Comment by ZEXSM** [comment]
Give an example in the format expectation is reality

**Comment by Pisaren** [comment]
When I execute next code
```
var builder = new ODataQueryBuilder().For<Model>()
	.ByList()
	.Filter(x => x.LongId == 1);
var uri = builder.ToDictionary();
```
I get empty dictionary, but expect a dictionary with one item: key="$filter", value="LongId eq 1".

**Comment by ZEXSM** [comment]
Hi. The resource must always be specified
