### ISSUE TITLE
Handling more types in Filter method

### ISSUE THREAD

**Issue by mwolszleger** [ZEXSM/OData.QueryBuilder#87]
Method ToQuery() in StringExtensions class doesn't handle` IEnumerable<long>` type (also double, float, DateTime). So it is impossible to create query "in (long/double/float/DateTime collection)"

**Comment by ZEXSM** [comment]
Hi recently closed a issue
https://github.com/ZEXSM/OData.QueryBuilder/issues/82
but i will check again

**Comment by ZEXSM** [comment]
Latest version handles (long/double/float/DateTime collection)
I close the issue
