### ISSUE TITLE
Support of cast function

### ISSUE THREAD

**Issue by Pisaren** [ZEXSM/OData.QueryBuilder#96]
It would be nice to have a support for OData _**cast**_ function for cases of searching by part of some ID's.
To construct queries like - _contains(cast(documentId, 'Edm.String'), '555')_

**Comment by ZEXSM** [comment]
contains(cast(documentId, 'Edm.String'), '555') 
PR https://github.com/OData/odata.net/pull/2231 - removed single quotes from type in cast function

if they are needed then
`.Filter((s, f) => f.Contains(f.Cast(s.ODataKindNew.ODataCode.Code, "'Edm.String'"), "55"))`
